WordScramble.Api/Controllers/HomeController.cs
using AutoMapper;
using MediatR;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace WordScramble.Api.Controllers
{
    public class HomeController : ControllerBase
    {
        public HomeController(IMediator mediator, IMapper mapper) 
            : base(mediator, mapper)
        {
        }

        public IActionResult Index()
        {
            return View();
        }
    }
}

WordScramble.Api/Controllers/LookupController.cs
using AutoMapper;
using MediatR;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using WordScramble.Domains;
using WordScramble.Domains.ViewModels;

namespace WordScramble.Api.Controllers
{
    public class LookupController : ControllerBase
    {
        private readonly ApplicationSettings applicationSettings;

        public LookupController(ApplicationSettings applicationSettings, IMediator mediator, IMapper mapper) : base(mediator, mapper)
        {
            this.applicationSettings = applicationSettings;
        }

        [HttpGet, Route("[controller]/{word}")]
        public IActionResult Index([FromRoute]string word)
        {
            return View(new LookupIndexViewModel { 
                DictionaryUriFormat = applicationSettings.DictionaryUriFormat,
                Word = word
            });
        }
    }
}

WordScramble.Api/Controllers/WordController.cs
using AutoMapper;
using MediatR;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using WordScramble.Domains.ViewModels;
using ScrambleWordRequest = WordScramble.Domains.Requests.ScrambleWord;
using GetWordRequest = WordScramble.Domains.Requests.GetWord;
using SolveWordRequest = WordScramble.Domains.Requests.SolveWord;
using System.Threading;

namespace WordScramble.Api.Controllers
{
    public class WordController : ControllerBase
    {
        [HttpGet, ActionName("Scramble")]
        public async Task<IActionResult> ScrambleWord(ScrambleWordRequestViewModel viewModel, CancellationToken cancellationToken)
        {
            var request = Mapper
                .Map<ScrambleWordRequest>(viewModel);

            var response = await Mediator
                .Send(request, cancellationToken);

            return ValidateResponse(response);
        }

        [HttpGet, ActionName("Random")]
        public async Task<IActionResult> GetRandomWord(GetWordRequestViewModel viewModel, CancellationToken cancellationToken)
        {
            var request = Mapper
                .Map<GetWordRequest>(viewModel);

            var response = await Mediator
                .Send(request, cancellationToken);

            return ValidateResponse(response);
        }

        [HttpGet, ActionName("Solve")]
        public async Task<IActionResult> SolveScrambledWord(SolveWordRequestViewModel viewModel, CancellationToken cancellationToken)
        {
            var request = Mapper
                .Map<SolveWordRequest>(viewModel);

            var response = await Mediator
                .Send(request, cancellationToken);

            return ValidateResponse(response);
        }


        public WordController(IMediator mediator, IMapper mapper)
            : base(mediator, mapper)
        {

        }
    }
}

WordScramble.Api/Views/Home/Index.cshtml
@model SolveWordRequestViewModel
    <ul class="nav nav-pills nav-fill d-none">
        <li class="nav-item">
            <a class="nav-link active" href="#">Multiplayer</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="#">Single Player</a>
        </li>
    </ul>
<div class="d-none">
    <h1 id="output">[Output here]</h1>
</div>
<form>
    <div class="form-group">
        <label for="wordText">Word:</label>
        <div class="input-group mb-3">
            <input id="wordText" 
                   type="text" 
                   class="form-control bg-secondary text-light" />
            <div class="input-group-append">
                <button class="btn btn-outline-secondary btn-secondary text-light" 
                        type="button" 
                        id="lookupButton">Lookup</button>
            </div>
        </div>
    </div>
    <div class="form-group">
        <label for="minimumLengthText">Minimum length:</label>
        <input id="minimumLengthText" value="5" min="3" max="@int.MaxValue"
               type="number" 
               class="form-control bg-secondary text-light" />
    </div>
    <button id="scrambleButton" 
            type="button" 
            class="btn btn-secondary">Scramble</button>
    <button id="randomButton" 
            type="button" 
            class="btn btn-secondary">Get Random Word</button>
</form>



@section bodyScripts{
    <script type="text/javascript">
        $(function () {
            $lookupButton = $("#lookupButton");
            $wordText = $("#wordText");
            $minimumLengthText = $("#minimumLengthText");
            $scrambleButton = $("#scrambleButton");
            $randomButton = $("#randomButton");
            $output = $("#output");
            $outputParent = $output.parent();
            $scrambleButton.on("click", function () {
                var wordTextVal = $wordText.val();
                if (wordTextVal.length) {
                    $.get('@Url.Action("Scramble", "Word")', { word: wordTextVal },
                        function (e) {
                            $output.text(e);
                            $outputParent.removeClass("d-none");
                        });
                }
            });

            $lookupButton.on("click", function () {
                var wordTextVal = $wordText.val();
                if (wordTextVal.length) {
                    window.open('@Url.Action("Index", "Lookup")/' + wordTextVal);
                }
            });

            $randomButton.on("click", function () {
                var minimumLengthText = $minimumLengthText.val();

                if (!$minimumLengthText.length || isNaN(minimumLengthText)) {
                    minimumLengthText = 0;
                }

                $.get('@Url.Action("Random", "Word")', { minimumLength: minimumLengthText }, 
                    function (e) { $wordText.val(e)  })
            });
        });
    </script>
}

WordScramble.Api/Views/Lookup/index.cshtml
@model LookupIndexViewModel
@section headerScripts {
    <style type="text/css">
        iframe {
            width: 100%;
            border: none;
            margin:0;
            padding:0;
        }
    </style>
}

<div id="hide-panel" class="card">
    <button id="back-button" class="btn btn-primary">Go Back</button>
</div>
<iframe src="@string.Format(Model.DictionaryUriFormat, Model.Word)"></iframe>

@section bodyScripts {
    <script type="text/javascript">
        $(function () {
            var $iFrames = $("iframe");
            var $backButton = $("#back-button");

            $backButton.on("click", function () {
                window.close();
            });

            $iFrames.height(window.innerHeight - $backButton.height());
        });
    </script>
}

WordScramble.Api/Views/Shared/Layout.cshtml
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Word Scramble</title>
    <link rel="stylesheet"
          href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
          integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
          crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.4.1.min.js"
            crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
            integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
            crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
            integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
            crossorigin="anonymous"></script>

    <style type="text/css">
        body {
            background-color: #343a40;
        }
    </style>
    @await RenderSectionAsync("headerScripts", false)
</head>
<body>
    <div class="container bg-dark text-light">
        @RenderBody()
    </div>

    @await RenderSectionAsync("bodyScripts", false)
</body>
</html>